In [1]:
#Importe de librerías a usar
import pandas as pd
import csv
import ast
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#Leo los archivos
df_reviews = pd.read_csv("df_reviews_data.csv")
df_items = pd.read_parquet("df_items_sample.parquet")
df_games = pd.read_csv("df_games_data.csv")

In [5]:
df_games

,genres,app_name,title,release_date,tags,id
0,['Action'],Bioshock Infinite: Columbia's Finest,Bioshock Infinite: Columbia's Finest,2013,"['Action', 'FPS']",2028850
1,"['Action', 'Adventure']",Assassin’s Creed® III Season Pass,Assassin’s Creed® III Season Pass,2012,"['Action', 'Adventure']",2028103
2,['Action'],Call of Duty®: Black Ops II Season Pass,Call of Duty®: Black Ops II Season Pass,2013,"['Action', 'FPS', 'Zombies', 'Multiplayer']",2028062
3,['Strategy'],Worms Revolution Season Pass,Worms Revolution Season Pass,2012,['Strategy'],2028056
4,['Action'],Tom Clancy's Ghost Recon Future Soldier - Seas...,Tom Clancy's Ghost Recon Future Soldier - Seas...,2012,['Action'],2028055
...,...,...,...,...,...,...
29749,['Action'],Half-Life: Opposing Force,Half-Life: Opposing Force,1999,"['FPS', 'Action', 'Sci-fi', 'Singleplayer', 'C...",50
29750,['Action'],Deathmatch Classic,Deathmatch Classic,2001,"['Action', 'FPS', 'Multiplayer', 'Classic', 'S...",40
29751,['Action'],Day of Defeat,Day of Defeat,2003,"['FPS', 'World War II', 'Multiplayer', 'Action...",30
29752,['Action'],Team Fortress Classic,Team Fortress Classic,1999,"['Action', 'FPS', 'Multiplayer', 'Classic', 'S...",20
29753,['Action'],Counter-Strike,Counter-Strike,2000,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",10

In [6]:
df_items

,user_id,item_id,item_name,playtime_forever,tags_and_genres
0,76561198067278492,8800,Sid Meier's Civilization IV: Beyond the Sword,0.0,"Strategy, Turn-Based Strategy, 4X, Turn-Based,..."
1,76561198058241886,209000,Batman™: Arkham Origins,566.0,"Action, Batman, Open World, Superhero, Adventu..."
2,alexisacoolhuman,104200,BEEP,8.0,"Indie, Platformer, Adventure, Puzzle, Singlepl..."
3,76561198050122465,250420,8BitMMO,30.0,"Free to Play, Massively Multiplayer, Sandbox, ..."
4,76561198061904130,253960,Jack Orlando Director's Cut,0.0,"Adventure, Point & Click, Noir, Singleplayer, ..."
...,...,...,...,...,...
49995,ZanToR,12360,FlatOut: Ultimate Carnage,0.0,"Racing, Destruction, Multiplayer, Arcade, Acti..."
49996,Andi-mc-chan,15390,Brothers in Arms: Hell's Highway,175.0,"Action, World War II, FPS, Tactical, Singlepla..."
49997,mda7,369640,Treeker: The Lost Glasses,299.0,"Indie, Adventure, First-Person, Platformer, Ad..."
49998,76561198030672315,9180,Commander Keen Complete Pack,0.0,"Platformer, Classic, Action, 2D, Retro, 1990's..."
49999,76561198060495473,242720,GunZ 2: The Second Duel,77.0,"Free to Play, Action, Multiplayer, Third-Perso..."

In [7]:
df_reviews

                 user_id  sentiment_analysis  posted  item_id  recommend
0      76561197970982479                   1    2011     1250       True
1      76561197970982479                   1    2011    22200       True
2      76561197970982479                   1    2011    43110       True
3                js41637                   1    2014   251610       True
4                js41637                   1    2013   227300       True
...                  ...                 ...     ...      ...        ...
48493            wayfeng                   1    2015      730       True
48494  76561198251004808                   2    2015   253980       True
48495        72947282842                   0    2015      730       True
48496          ApxLGhost                   1    2015      730       True
48497  76561198267374962                   2    2015   369200       True

[48498 rows x 5 columns]

In [3]:
#def PlayTimeGenre( genero : str ): # Debe devolver año con mas horas jugadas para dicho género.
#Ejemplo de retorno: {"Año de lanzamiento con más horas jugadas para Género X" : 2013}

SyntaxError: invalid syntax (140185258.py, line 1)

In [74]:
cadena_a_buscar = "Sci-fi"
resultados = df_items[df_items['tags_and_genres'].str.contains(cadena_a_buscar, case=False, na=False)]

# Supongamos que tienes un DataFrame llamado df_items

# Agrupa por la columna 'item_id' y suma la columna 'playtime_forever'
resultados2 = resultados.groupby('item_id')['playtime_forever'].sum().reset_index()
resultados2
# 'resultados' ahora contiene la suma de 'playtime_forever' por 'item_id'

     item_id  playtime_forever
0         40          154424.0
1         50          726545.0
2         60          156923.0
3         70         2650946.0
4        130          436838.0
..       ...               ...
902   504050             350.0
903   504490            8809.0
904   504750             366.0
905   513580             801.0
906   525350               0.0

[907 rows x 2 columns]

In [76]:
# Suponiendo que 'resultados' es el DataFrame con la suma de 'playtime_forever' por 'item_id'
# Y 'df_games' es el DataFrame con los datos de los juegos

# Fusiona 'resultados' con 'df_games' usando 'item_id' como clave
merged_df = pd.merge(resultados2, df_games[['id', 'release_date']], left_on='item_id', right_on='id', how='left')

# Encuentra la fila con la suma máxima de 'playtime_forever'
fila_max_playtime = merged_df[merged_df['playtime_forever'] == merged_df['playtime_forever'].max()]

# Obtiene la fecha de lanzamiento correspondiente
fecha_lanzamiento_max_playtime = fila_max_playtime['release_date'].values[0]

int(fecha_lanzamiento_max_playtime)

2013

In [19]:
#def UserForGenre( genero : str ): Debe devolver el usuario que acumula más horas jugadas para el género dado y una lista de la acumulación de horas jugadas por año.
#Ejemplo de retorno: {"Usuario con más horas jugadas para Género X" : us213ndjss09sdf, "Horas jugadas":[{Año: 2013, Horas: 203}, {Año: 2012, Horas: 100}, {Año: 2011, Horas: 23}]}

SyntaxError: invalid syntax (1230112370.py, line 1)

In [27]:
cadena_a_buscar = "FPS"
resultados = df_items[df_items['tags_and_genres'].str.contains(cadena_a_buscar, case=False, na=False)]

# Supongamos que tienes un DataFrame llamado df_items

# Agrupa por la columna 'user_id' y suma la columna 'playtime_forever'
resultados2 = resultados.groupby('user_id')['playtime_forever'].sum().reset_index()
resultados2 = resultados2.sort_values(['playtime_forever'], ascending= False)
userbuscado = resultados2.iloc[0]

resultados3 = df_items[(df_items['user_id'] == userbuscado['user_id']) & (df_items['tags_and_genres'].str.contains(cadena_a_buscar, case=False, na=False))]

resultados3 = resultados3.sort_values(['playtime_forever'], ascending= False)
# 'resultados' ahora contiene la suma de 'playtime_forever' por 'item_id'

resultados4 = pd.merge(resultados3, df_games[['id', 'release_date']], left_on='item_id', right_on='id', how='left')


resultados4 = pd.merge(resultados3, df_games[['id', 'release_date']], left_on='item_id', right_on='id', how='left')
resultados4 = resultados4.groupby('release_date')['playtime_forever'].sum().reset_index()
resultados4 = resultados4.sort_values(['release_date'], ascending= False)


# Filtrar las filas donde 'playtime_forever' sea mayor que 0 y crear una lista de tuplas
lista_anos_horas = [(f"Año: {int(ano)}", f"Horas: {int(hora)}") for ano, hora in zip(resultados4['release_date'], resultados4['playtime_forever'] / 60) if hora > 0]
lista_anos_horas.insert(0,{"El usuario con mas horas jugados para el genero es",userbuscado['user_id']})
# Imprimir la lista de años y horas
print(lista_anos_horas)

[{'El usuario con mas horas jugados para el genero es', '76561197996330176'}, ('Año: 2000', 'Horas: 4007')]

In [ ]:
#def UsersRecommend( año : int ): Devuelve el top 3 de juegos MÁS recomendados por usuarios para el año dado. (reviews.recommend = True y comentarios positivos/neutrales)
#Ejemplo de retorno: [{"Puesto 1" : X}, {"Puesto 2" : Y},{"Puesto 3" : Z}]

In [47]:
year_buscado = 2014
recommend_year = df_reviews[df_reviews['posted'] == year_buscado]

recommend_true = recommend_year[recommend_year['recommend'] & ((recommend_year['sentiment_analysis'] == 1) | (recommend_year['sentiment_analysis'] == 2))]

top3most = recommend_true.groupby('item_id')['sentiment_analysis'].count().reset_index()

top3most = pd.merge(top3most, df_games[['id', 'title']], left_on='item_id', right_on='id', how='left')

top3m = top3most.sort_values(['sentiment_analysis'], ascending= False).head(3)

listafuncion = [(f'Puesto {i + 1}', top3m['title'].iloc[i]) for i in range(len(top3m))]

print(listafuncion)

[('Puesto 1', 'Team Fortress 2'), ('Puesto 2', 'Counter-Strike: Global Offensive'), ('Puesto 3', "Garry's Mod")]

In [ ]:
#def UsersNotRecommend( año : int ): Devuelve el top 3 de juegos MENOS recomendados por usuarios para el año dado. (reviews.recommend = False y comentarios negativos)
#Ejemplo de retorno: [{"Puesto 1" : X}, {"Puesto 2" : Y},{"Puesto 3" : Z}]

In [25]:
year_buscado = 2014
recommend_year = df_reviews[df_reviews['posted'] == year_buscado]

recommend_false = recommend_year[recommend_year['recommend'] == False & ((recommend_year['sentiment_analysis'] == 0) )]

top3least = recommend_false.groupby('item_id')['sentiment_analysis'].count().reset_index()

top3least = pd.merge(top3least, df_games[['id', 'title']], left_on='item_id', right_on='id', how='left')

top3l = top3least.sort_values(['sentiment_analysis'], ascending= False).head(3)

listafuncion = [(f'Puesto {i + 1}', top3l['title'].iloc[i]) for i in range(len(top3l))]

print(listafuncion)

[('Puesto 1', 'DayZ'), ('Puesto 2', 'Counter-Strike: Global Offensive'), ('Puesto 3', nan)]

In [48]:
# def sentiment_analysis( año : int ): Según el año de lanzamiento, se devuelve una lista con la cantidad de registros de reseñas de usuarios que se encuentren categorizados con un análisis de sentimiento.

SyntaxError: invalid syntax (2164178567.py, line 1)

In [33]:
year_buscado = 2015
sentiment_year = df_reviews[df_reviews['posted'] == year_buscado]
sentiment_year = sentiment_year.groupby('sentiment_analysis').size().reset_index(name='count')

listafuncion = []
listafuncion.insert(0,"Segun el año de lanzamiento "+ str(year_buscado))
listafuncion.insert(1, "Análisis de Sentimiento negativos : " + str(sentiment_year['count'].iloc[0]))
listafuncion.insert(2, "Análisis de Sentimiento neutrales : " + str(sentiment_year['count'].iloc[1]))
listafuncion.insert(3, "Análisis de Sentimiento positivos : " + str(sentiment_year['count'].iloc[2]))

print(listafuncion)

['Segun el año de lanzamiento 2015', 'Análisis de Sentimiento negativos : 1786', 'Análisis de Sentimiento neutrales : 11676', 'Análisis de Sentimiento positivos : 4692']

In [ ]:
for index, row in sentiment_year.iterrows():
    if row['sentiment_analysis'] == 0:
        listafuncion.append('Analisis de Sentimiento negativos')
        listafuncion.append(row['count'])
    elif row['sentiment_analysis'] == 1:
        listafuncion.append('Analisis de Sentimiento neutrales')
        listafuncion.append(row['count'])
    else :
        listafuncion.append('Analisis de Sentimiento positivos')
        listafuncion.append(row['count'])

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def recommend_games(product_id, num_recommendations=5):
    try:
        # Obtén el juego de referencia
        target_game = df_games[df_games['id'] == product_id]

        if target_game.empty:
            return {"message": "No se encontró el juego de referencia."}

        # Combina las etiquetas (tags) y géneros en una sola cadena de texto
        target_game_tags_and_genres = ' '.join(target_game['tags'].fillna('') + ' ' + target_game['genres'].fillna(''))

        # Crea un vectorizador TF-IDF y ajústalo una vez
        tfidf_vectorizer = TfidfVectorizer()
        tfidf_matrix = tfidf_vectorizer.fit_transform(df_games['tags'].fillna('') + ' ' + df_games['genres'].fillna(''))

        # Calcula la similitud entre el juego de referencia y todos los juegos
        similarity_scores = cosine_similarity(tfidf_vectorizer.transform([target_game_tags_and_genres]), tfidf_matrix)

        # Obtiene los índices de los juegos más similares
        similar_games_indices = similarity_scores[0].argsort()[::-1]

        # Recomienda los juegos más similares
        recommended_games = df_games.loc[similar_games_indices[1:num_recommendations + 1]]

        # Devuelve la lista de juegos recomendados
        return recommended_games[['title']].to_dict(orient='records')

    except Exception as e:
        return {"message": f"Error: {str(e)}"}

In [38]:
recommend_games(10)

[{'title': 'Counter-Strike: Source'},
 {'title': 'Counter-Strike: Condition Zero'},
 {'title': 'Insurgency'},
 {'title': 'Umbrella Corps™/Biohazard Umbrella Corps™'},
 {'title': 'Counter-Strike: Global Offensive'}]

In [17]:
df_items_sample = pd.read_parquet("df_items_sample.parquet")

In [21]:
df_games.sort_values('id')

,genres,app_name,title,release_date,tags,id
29753,['Action'],Counter-Strike,Counter-Strike,2000,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...",10
29752,['Action'],Team Fortress Classic,Team Fortress Classic,1999,"['Action', 'FPS', 'Multiplayer', 'Classic', 'S...",20
29751,['Action'],Day of Defeat,Day of Defeat,2003,"['FPS', 'World War II', 'Multiplayer', 'Action...",30
29750,['Action'],Deathmatch Classic,Deathmatch Classic,2001,"['Action', 'FPS', 'Multiplayer', 'Classic', 'S...",40
29749,['Action'],Half-Life: Opposing Force,Half-Life: Opposing Force,1999,"['FPS', 'Action', 'Sci-fi', 'Singleplayer', 'C...",50
...,...,...,...,...,...,...
4,['Action'],Tom Clancy's Ghost Recon Future Soldier - Seas...,Tom Clancy's Ghost Recon Future Soldier - Seas...,2012,['Action'],2028055
3,['Strategy'],Worms Revolution Season Pass,Worms Revolution Season Pass,2012,['Strategy'],2028056
2,['Action'],Call of Duty®: Black Ops II Season Pass,Call of Duty®: Black Ops II Season Pass,2013,"['Action', 'FPS', 'Zombies', 'Multiplayer']",2028062
1,"['Action', 'Adventure']",Assassin’s Creed® III Season Pass,Assassin’s Creed® III Season Pass,2012,"['Action', 'Adventure']",2028103
0,['Action'],Bioshock Infinite: Columbia's Finest,Bioshock Infinite: Columbia's Finest,2013,"['Action', 'FPS']",2028850